// Censo ANP/RenovaBio 2025 — 163 distribuidoras (fonte: 08-censo-nacional-completo.md)
export type Distribuidora = { rs: string; meta: number; pct: number | null; obs: string };

export const TOTAL_CBIOS = 46_126_199;

export const DISTRIBUIDORAS: Distribuidora[] = [
  { rs: "VIBRA ENERGIA S.A.", meta: 8191964, pct: 98.86, obs: "" },
  { rs: "IPIRANGA PRODUTOS DE PETRÓLEO S.A", meta: 6809481, pct: 100.0, obs: "" },
  { rs: "RAIZEN S.A.", meta: 5848597, pct: 100.0, obs: "" },
  { rs: "LARCO COMERCIAL DE PRODUTOS DE PETRÓLEO LTDA.", meta: 2956485, pct: 100.0, obs: "" },
  { rs: "ROYAL FIC DISTRIBUIDORA DE DERIVADOS DE PETRÓLEO S/A", meta: 2283565, pct: 30.89, obs: "Aposentou 1.578.225 em janeiro de 2026" },
  { rs: "TDC DISTRIBUIDORA DE COMBUSTÍVEIS S/A.", meta: 1246601, pct: 31.19, obs: "" },
  { rs: "ASTER PETRÓLEO LTDA.", meta: 1116733, pct: 0.0, obs: "" },
  { rs: "ALESAT COMBUSTÍVEIS S. A.", meta: 848301, pct: 100.0, obs: "" },
  { rs: "PETRÓLEO SABBÁ S.A.", meta: 707363, pct: 100.0, obs: "" },
  { rs: "ATEM' S DISTRIBUIDORA DE PETRÓLEO S.A.", meta: 676389, pct: 100.0, obs: "" },
  { rs: "PETROBAHIA S/A", meta: 636760, pct: 100.0, obs: "" },
  { rs: "CIAPETRO DISTRIBUIDORA DE COMBUSTÍVEIS LTDA", meta: 616950, pct: 100.0, obs: "Sub judice" },
  { rs: "SIM DISTRIBUIDORA DE COMBUSTIVEIS LTDA", meta: 494257, pct: 100.0, obs: "" },
  { rs: "FEDERAL ENERGIA S/A", meta: 484553, pct: 100.0, obs: "" },
  { rs: "DISTRIBUIDORA EQUADOR DE PRODUTOS DE PETRÓLEO LTDA.", meta: 435577, pct: 100.0, obs: "" },
  { rs: "RODOIL DISTRIBUIDORA DE COMBUSTÍVEIS LTDA", meta: 433434, pct: 85.0, obs: "" },
  { rs: "POTENCIAL PETRÓLEO LTDA", meta: 401252, pct: 100.0, obs: "" },
  { rs: "FLEXPETRO DISTRIBUIDORA DE DERIVADOS DE PETRÓLEO S.A.", meta: 394417, pct: 100.0, obs: "" },
  { rs: "TOBRAS DISTRIBUIDORA DE COMBUSTÍVEIS LTDA.", meta: 364316, pct: 100.0, obs: "" },
  { rs: "IMPERIO COMERCIO DE PETROLEO S/A.", meta: 347588, pct: 0.03, obs: "" },
  { rs: "RAIZEN MIME COMBUSTIVEIS S/A.", meta: 334851, pct: 100.0, obs: "" },
  { rs: "PETROX DISTRIBUIDORA LTDA.", meta: 307282, pct: 100.0, obs: "" },
  { rs: "DUVALE DISTRIBUIDORA DE PETRÓLEO E ÁLCOOL LTDA.", meta: 293412, pct: 0.0, obs: "" },
  { rs: "TEMAPE - TERMINAIS MARÍTIMOS DE PERNAMBUCO LTDA.", meta: 276206, pct: 100.0, obs: "" },
  { rs: "BIOPETRÓLEO DO BRASIL DISTRIBUIDORA DE COMBUSTÍVEIS LTDA", meta: 274128, pct: 100.0, obs: "" },
  { rs: "TAURUS DISTRIBUIDORA DE PETRÓLEO LTDA", meta: 273293, pct: 100.0, obs: "" },
  { rs: "SP INDÚSTRIA E DISTRIBUIDORA DE PETRÓLEO LTDA", meta: 257629, pct: 100.0, obs: "" },
  { rs: "ON PETRO - DISTRIBUIDORA DE COMBUSTIVEIS LTDA.", meta: 256348, pct: 100.0, obs: "" },
  { rs: "SANTA LUCIA DISTRIBUIDORA DE COMBUSTIVEIS LTDA", meta: 255002, pct: 100.0, obs: "" },
  { rs: "TOTALENERGIES DISTRIBUIDORA BRASIL LTDA", meta: 242890, pct: 100.0, obs: "" },
  { rs: "RDP ENERGIA LTDA", meta: 240280, pct: 100.0, obs: "" },
  { rs: "CENTROESTE DISTRIBUICAO DE DERIVADOS DE PETROLEO S/A", meta: 221186, pct: 100.0, obs: "" },
  { rs: "DISTRIBUIDORA TABOCÃO LTDA.", meta: 215157, pct: 0.0, obs: "" },
  { rs: "IMPERIAL DISTRIBUIDORA DE PETRÓLEO LTDA.", meta: 205015, pct: 100.0, obs: "" },
  { rs: "DISTRIBUIDORA DE COMBUSTÍVEIS SAARA S.A.", meta: 199726, pct: null, obs: "Sub judice" },
  { rs: "DISLUB COMBUSTIVEIS S.A.", meta: 196975, pct: 100.0, obs: "" },
  { rs: "ART PETRO DISTRIBUIDORA DE COMBUSTÍVEIS LTDA.", meta: 192751, pct: 100.0, obs: "Aposentou 23.759 CBIOs até 31/12/2025 referente a metas de a" },
  { rs: "STANG DISTRIBUIDORA DE PETRÓLEO LTDA.", meta: 191927, pct: 100.0, obs: "" },
  { rs: "GP DISTRIBUIDORA DE COMBUSTÍVEIS S/A.", meta: 191125, pct: 100.0, obs: "" },
  { rs: "D`MAIS DISTRIBUIDORA DE PETRÓLEO LTDA.", meta: 186777, pct: 100.0, obs: "" },
  { rs: "DISTRIBUIDORA RIO BRANCO DE PETRÓLEO LTDA.", meta: 182385, pct: 100.0, obs: "" },
  { rs: "RUMOS DISTRIBUIDORA DE PETRÓLEO LTDA.", meta: 175591, pct: 0.0, obs: "Sub judice" },
  { rs: "SETTA COMBUSTÍVEIS S/A.", meta: 174412, pct: 92.07, obs: "" },
  { rs: "MAX DISTRIBUIDORA DE PETRÓLEO LTDA.", meta: 171276, pct: 100.0, obs: "" },
  { rs: "COPERCANA DISTRIBUIDORA DE COMBUSTIVEIS LTDA", meta: 170584, pct: 100.0, obs: "" },
  { rs: "76 OIL DISTRIBUIDORA DE COMBUSTÍVEIS S/A", meta: 168838, pct: 86.44, obs: "" },
  { rs: "REDE SOL FUEL DISTRIBUIDORA S/A.", meta: 166136, pct: 100.0, obs: "" },
  { rs: "DISTRIBUIDORA DE PRODUTOS DE PETRÓLEO CHARRUA LTDA", meta: 164766, pct: 100.0, obs: "" },
  { rs: "WATT DISTRIBUIDORA BRASILEIRA DE COMBUSTÍVEIS E DERIVADOS DE PETRÓLEO LTDA", meta: 153382, pct: 100.0, obs: "" },
  { rs: "BIOPETRO DISTRIBUIDORA DE COMBUSTIVEIS", meta: 152114, pct: null, obs: "Sub judice" },
  { rs: "IDAZA DISTRIBUIDORA DE PETRÓLEO LTDA", meta: 148997, pct: 100.0, obs: "" },
  { rs: "ARAGUAIA DISTRIBUIDORA DE COMBUSTÍVEIS S.A", meta: 131533, pct: 0.0, obs: "" },
  { rs: "PETROGOIÁS DISTRIBUIDORA DE PETRÓLEO LTDA.", meta: 127801, pct: 0.0, obs: "" },
  { rs: "FLAGLER COMBUSTIVEIS S/A", meta: 127047, pct: 85.78, obs: "" },
  { rs: "RUFF CJ DISTRIBUIDORA DE PETRÓLEO LTDA", meta: 122432, pct: 100.0, obs: "" },
  { rs: "DIBRAPE DISTRIBUIDORA BRASILEIRA DE PETRÓLEO LTDA.", meta: 122295, pct: 100.0, obs: "" },
  { rs: "ATLÂNTICA PRODUTOS DE PETRÓLEO LTDA.", meta: 122008, pct: 100.0, obs: "" },
  { rs: "SR BRASIL PETRÓLEO LTDA.", meta: 108736, pct: 100.0, obs: "" },
  { rs: "PETROLUZ DISTRIBUIDORA LTDA.", meta: 108610, pct: 100.0, obs: "" },
  { rs: "SMALL DISTRIBUIDORA DE DERIVADOS DE PETRÓLEO LTDA.", meta: 107722, pct: 100.0, obs: "" },
  { rs: "DISTRIBUIDORA SUL DE PETRÓLEO LTDA.", meta: 102641, pct: 100.0, obs: "" },
  { rs: "ESTRADA DISTRIBUIDORA DE DERIVADOS DE PETRÓLEO LTDA.", meta: 100385, pct: 100.0, obs: "" },
  { rs: "HORA DISTRIBUIDORA DE PETRÓLEO LTDA.", meta: 95963, pct: 100.0, obs: "" },
  { rs: "NIMO ERNERGIA DISTRIBUIDORA E COMERCIO DE COMBUSTIVEIS LIMITADA", meta: 95631, pct: 100.0, obs: "" },
  { rs: "PETROWORLD COMBUSTIVEIS S/A", meta: 94830, pct: 5.2, obs: "Sub judice" },
  { rs: "DANPETRO DISTRIBUIDORA DE PETRÓLEO S.A.", meta: 93673, pct: 100.0, obs: "" },
  { rs: "SADA COMBUSTÍVEIS LTDA", meta: 93027, pct: 100.0, obs: "" },
  { rs: "SOLL DISTRIBUIDORA DE PETRÓLEO LTDA", meta: 91287, pct: 100.0, obs: "" },
  { rs: "REALCOOL DISTRIBUIDORA DE PETROLEO LTDA", meta: 91226, pct: 100.0, obs: "" },
  { rs: "FGC DISTRIBUIDORA DE COMBUSTIVEIS LTDA", meta: 90925, pct: 0.0, obs: "Sub judice" },
  { rs: "ALPES DISTRIBUIDORA DE PETRÓLEO LTDA.", meta: 83893, pct: 0.0, obs: "" },
  { rs: "FAN - DISTRIBUIDORA DE PETRÓLEO LTDA.", meta: 82923, pct: 100.0, obs: "" },
  { rs: "GOL COMBUSTÍVEIS S.A", meta: 77292, pct: null, obs: "Sub judice" },
  { rs: "DISTRIBUIDORA DE COMBUSTÍVEL TORRÃO LTDA.", meta: 74596, pct: 100.0, obs: "" },
  { rs: "TOWER BRASIL PETRÓLEO LTDA.", meta: 74288, pct: 100.0, obs: "" },
  { rs: "MAXSUL DISTRIBUIDORA DE COMBUSTÍVEIS LTDA.", meta: 72235, pct: 100.0, obs: "" },
  { rs: "PONTUAL BRASIL PETRÓLEO LTDA", meta: 71420, pct: 100.0, obs: "" },
  { rs: "FERA LUBRIFICANTES LTDA.", meta: 66333, pct: 86.12, obs: "" },
  { rs: "REDEPETRO DISTRIBUIDORA DE PETRÓLEO LTDA.", meta: 66179, pct: 100.0, obs: "" },
  { rs: "GREEN DISTRIBUIDORA DE PETRÓLEO LTDA", meta: 65269, pct: 100.0, obs: "Sub judice" },
  { rs: "PETROSERRA DISTRIBUIDORA DE PETRÓLEO LTDA", meta: 64988, pct: 100.0, obs: "" },
  { rs: "ALCOOLBRAS - ÁLCOOL DO BRASIL DISTRIBUIDORA DE COMBUSTÍVEIS LTDA.", meta: 64232, pct: 100.0, obs: "" },
  { rs: "INTEGRACAO COMBUSTIVEIS LTDA", meta: 61489, pct: 100.0, obs: "" },
  { rs: "WK PRODUTOS DE PETROLEO LTDA", meta: 57278, pct: 100.0, obs: "" },
  { rs: "MONTE CABRAL DISTRIBUIDORA DE COMBUSTÍVEIS LTDA.", meta: 56284, pct: 35.7, obs: "" },
  { rs: "STOCK DISTRIBUIDORA DE PETRÓLEO LTDA", meta: 54075, pct: 0.0, obs: "" },
  { rs: "J.R DISTRIBUIDORA DE PETRÓLEO LTDA", meta: 53656, pct: 100.0, obs: "" },
  { rs: "PETRORIENTE DISTRIBUIDORA DE COMBUSTIVEIS S.A", meta: 52630, pct: 0.0, obs: "" },
  { rs: "DISTRIBUIDORA DE COMBUSTIVEIS MASUT LTDA", meta: 47106, pct: 100.0, obs: "" },
  { rs: "CENTRO OESTE BRASIL PETRÓLEO LTDA.", meta: 47033, pct: 45.83, obs: "Aposentou 43.870  CBIOs em 2026." },
  { rs: "FÉLIX DISTRIBUIDORA DE COMBUSTÍVEIS LTDA", meta: 46369, pct: 100.0, obs: "" },
  { rs: "ECO DISTRIBUIDORA DE PETROLEO S A", meta: 43621, pct: 24.94, obs: "Sub judice" },
  { rs: "ESTRELA * DISTRIBUIDORA DE COMBUSTIVEIS LIMITADA.", meta: 43586, pct: 0.0, obs: "" },
  { rs: "TRIANGULO DISTRIBUIDORA DE PETRÓLEO LTDA", meta: 35085, pct: 100.0, obs: "" },
  { rs: "NOROESTE DISTIBUIDORA DE COMBUSTÍVEIS LTDA.", meta: 31030, pct: 0.0, obs: "" },
  { rs: "PETROEXPRESS DISTRIBUIDORA DE COMBUSTÍVEIS E DERIVADOS DE PETRÓLEO LTDA.", meta: 30473, pct: 100.0, obs: "" },
  { rs: "GAZ PRIME DISTRIBUIDORA DE COMBUSTIVEIS LTDA", meta: 29765, pct: 0.0, obs: "Sub judice" },
  { rs: "MAXXI DISTRIBUIDORA DE PETRÓLEO LTDA.", meta: 29276, pct: 100.0, obs: "" },
  { rs: "LIDERPETRO DISTRIBUIDORA DE PETRÓLEO LTDA", meta: 29009, pct: 100.0, obs: "" },
  { rs: "AMERICANOIL DISTRIBUIDORA DE DERIVADOS DE PETRÓLEO EIRELI", meta: 27323, pct: 100.0, obs: "" },
  { rs: "PETRO NORTE DISTRIBUIDORA DE PETROLEO LTDA", meta: 26248, pct: 100.0, obs: "" },
  { rs: "WALENDOWSKY DISTRIBUIDORA DE COMBUSTÍVEIS LTDA", meta: 26187, pct: 100.0, obs: "" },
  { rs: "PETRONAC DISTRIBUIDORA NACIONAL DE DERIVADOS DE PETRÓLEO E ALCOOL LTDA", meta: 25924, pct: 100.0, obs: "Sub judice" },
  { rs: "CRUZ DE MALTA DISTRIBUIDORA DE PETRÓLEO LTDA.", meta: 25912, pct: 100.0, obs: "" },
  { rs: "YPETRO DISTRIBUIDORA DE COMBUSTIVEIS S.A.", meta: 25019, pct: 100.0, obs: "" },
  { rs: "MAR AZUL DISTRIBUIDORA DE COMBUSTIVEIS LTDA", meta: 24474, pct: 0.0, obs: "Sub judice" },
  { rs: "RM PETRÓLEO LTDA", meta: 24187, pct: 100.0, obs: "" },
  { rs: "PHAENARETE DISTRIBUIDORA DE COMBUSTIVEIS LTDA", meta: 23661, pct: 77.34, obs: "Aposentou  41.361  CBIOs em 2026." },
  { rs: "SIMARELLI DISTRIBUIDORA DE DERIVADOS DE PETRÓLEO LTDA.", meta: 22757, pct: 100.0, obs: "" },
  { rs: "ASPEN DISTRIBUIDORA DE COMBUSTÍVEIS LTDA", meta: 21555, pct: null, obs: "Sub judice" },
  { rs: "EVEREST DISTRIBUIDORA DE COMBUSTIVEIS LTDA", meta: 19628, pct: 0.0, obs: "" },
  { rs: "PETROALCOOL DISTRIBUIDORA DE PETRÓLEO LTDA.", meta: 19342, pct: 100.0, obs: "Sub judice" },
  { rs: "RZD DISTRIBUIDORA DE DERIVADOS DE PETRÓLEO LTDA.", meta: 18110, pct: 100.0, obs: "" },
  { rs: "TAG DISTRIBUIDORA DE COMBUSTÍVEIS S/A.", meta: 16902, pct: 100.0, obs: "" },
  { rs: "ACOL DISTRIBUIDORA DE COMBUSTÍVEIS LTDA.", meta: 16111, pct: 100.0, obs: "" },
  { rs: "PELIKANO DISTRIBUIDORA DE PETRÓLEO LTDA", meta: 15868, pct: 100.0, obs: "" },
  { rs: "BRASPETRO DISTRIBUIDORA DE PETROLEO LTDA.", meta: 14803, pct: 100.0, obs: "" },
  { rs: "RODOPETRO DISTRIBUIDORA DE PETRÓLEO LTDA.", meta: 14411, pct: 48.93, obs: "" },
  { rs: "PARANAPANEMA DISTRIBUIDORA DE COMBUSTIVEIS EIRELI", meta: 14120, pct: 100.0, obs: "" },
  { rs: "VAISHIA DISTRIBUIDORA E TRANSPORTADORA DE COMBUSTIVEIS EIRELI", meta: 13905, pct: 100.0, obs: "" },
  { rs: "ATLANTA DISTRIBUIDORA DE PETRÓLEO LTDA.", meta: 11759, pct: 100.0, obs: "" },
  { rs: "ALL DISTRIBUIDORA DE COMBUSTÍVEIS EIRELI", meta: 11434, pct: 100.0, obs: "" },
  { rs: "UNI COMBUSTÍVEIS LTDA", meta: 11417, pct: 100.0, obs: "" },
  { rs: "IGUATEMI PETROLEO LTDA", meta: 9079, pct: 100.0, obs: "" },
  { rs: "BP COMERCIALIZADORA DE ENERGIA LTDA", meta: 8848, pct: 100.0, obs: "" },
  { rs: "BV DISTRIBUIDORA DE COMBUSTÍVEIS LTDA", meta: 7843, pct: 100.0, obs: "" },
  { rs: "MEG DISTRIBUIDORA DE COMBUSTIVEIS LTDA", meta: 7668, pct: 97.74, obs: "" },
  { rs: "DISTRIBUIDORA MONTEPETRO DE PETRÓLEO LTDA.", meta: 7371, pct: 100.0, obs: "" },
  { rs: "ECOMAT - ECOLÓGICA MATO GROSSO INDÚSTRIA E COMÉRCIO LTDA.", meta: 6303, pct: 100.0, obs: "" },
  { rs: "DIRECIONAL DISTRIBUIDORA DE DERIVADOS DE PETRÓLEO LTDA.", meta: 5770, pct: 100.0, obs: "" },
  { rs: "BEST FUEL DISTRIBUIDORA DE PETROLEO LTDA", meta: 5553, pct: 0.0, obs: "" },
  { rs: "PETROSALVADOR DISTRIBUIDORA DE COMBUSTÍVEIS LTDA.", meta: 4805, pct: 0.0, obs: "" },
  { rs: "ACAI PETROLEO MATO GROSSO LTDA", meta: 4269, pct: 100.0, obs: "" },
  { rs: "PETRONOL DISTRIBUIDORA DE PETRÓLEO E ETANOL LTDA.", meta: 2502, pct: 100.0, obs: "" },
  { rs: "MINUANO PETRÓLEO LTDA.", meta: 1587, pct: 9.58, obs: "" },
  { rs: "AVANT COMBUSTIVEIS LTDA", meta: 1198, pct: 100.0, obs: "" },
  { rs: "PETROTORQUE JC DISTRIBUIDORA DE COMBUSTIVEIS EIRELI", meta: 972, pct: 0.0, obs: "" },
  { rs: "TRANSO COMBUSTÍVEIS LTDA", meta: 874, pct: 100.0, obs: "" },
  { rs: "PETROSUL DISTRIBUIDORA TRANSPORTADORA E COMÉRCIO DE COMBUSTÍVEIS LTDA", meta: 840, pct: 100.0, obs: "" },
  { rs: "ECOLÓGICA DISTRIBUIDORA DE COMBUSTÍVEIS LTDA.", meta: 836, pct: 100.0, obs: "" },
  { rs: "MONTE ALEGRE COMBUSTIVEIS LTDA.", meta: 788, pct: 100.0, obs: "" },
  { rs: "COMÉRCIO DE DERIVADOS DE PETRÓLEO ISABELLA LTDA.", meta: 608, pct: 100.0, obs: "" },
  { rs: "GRAN PETRO DISTRIBUIDORA DE COMBUSTÍVEIS LTDA.", meta: 554, pct: 100.0, obs: "" },
  { rs: "RAVATO DISTRIBUIDORA DE COMBUSTIVEIS LTDA.", meta: 453, pct: 11.26, obs: "" },
  { rs: "ARKA DISTRIBUIDORA DE COMBUSTIVEIS LTDA", meta: 427, pct: 100.0, obs: "" },
  { rs: "MIDAS DISTRIBUIDORA DE COMBUSTIVEIS LTDA.", meta: 338, pct: 100.0, obs: "" },
  { rs: "PETROQUALITY DISTRIBUIDORA DE COMBUSTÍVEIS LTDA.", meta: 313, pct: 100.0, obs: "" },
  { rs: "ARAPETRO DISTRIBUIDORA DE PETRÓLEO LTDA.", meta: 294, pct: 100.0, obs: "" },
  { rs: "VMR DISTRIBUIDORA DE COMBUSTIVEIS E LUBRIFICANTES LTDA.", meta: 286, pct: 100.0, obs: "" },
  { rs: "MAXIMUS DISTRIBUIDORA DE COMBUSTIVEIS LTDA", meta: 234, pct: 100.0, obs: "" },
  { rs: "MANGUINHOS DISTRIBUIDORA S. A.", meta: 135, pct: 100.0, obs: "" },
  { rs: "MONVALE DISTRIBUIDORA DE PETRÓLEO LTDA", meta: 46, pct: 100.0, obs: "" },
  { rs: "BIOSTRATUM DISTRIBUIDORA DE COMBUSTÍVEIS LTDA", meta: 42, pct: 100.0, obs: "" },
  { rs: "SAFRA DISTRIBUIDORA DE PETROLEO S.A", meta: 27, pct: 0.0, obs: "" },
  { rs: "FLAG DISTRIBUIDORA DE PETRÓLEO LTDA.", meta: 23, pct: 100.0, obs: "" },
  { rs: "PETRO AMAZON PETRÓLEO DA AMAZONIA LTDA", meta: 12, pct: 100.0, obs: "" },
  { rs: "E. A. - ENERGIA AVANCADA LTDA", meta: 10, pct: 100.0, obs: "" },
  { rs: "TERRA BRASIL DISTRIBUIDORA DE PETRÓLEO LTDA", meta: 8, pct: 100.0, obs: "" },
  { rs: "JACAR DISTRIBUIDORA DE PETRÓLEO LTDA.", meta: 4, pct: 100.0, obs: "" },
  { rs: "PHOENIX DISTRIBUIDORA DE COMBUSTÍVEIS LTDA.", meta: 4, pct: 100.0, obs: "" },
  { rs: "START PETROLEO LTDA", meta: 4, pct: 100.0, obs: "" },
  { rs: "VELOX DISTRIBUIDORA DE COMBUSTIVEIS LTDA", meta: 4, pct: 100.0, obs: "" },
  { rs: "REAL DISTRIBUIDORA DE PETROLEO LTDA", meta: 1, pct: 100.0, obs: "" },
];

export function tier(m: number): 1 | 2 | 3 | 4 {
  return m >= 2_000_000 ? 1 : m >= 500_000 ? 2 : m >= 100_000 ? 3 : 4;
}

export const TIERS = [
  { id: 1, nome: "G1 · Maiores obrigações", crit: "≥ 2.000.000 CBIOs", serv: "Compra e aposentadoria em escala: preço, janela de compra e caixa" },
  { id: 2, nome: "G2 · Grandes", crit: "500 mil – 2 mi CBIOs", serv: "Meta de CBIO planejada junto com a compra de biocombustíveis" },
  { id: 3, nome: "G3 · Médias", crit: "100 – 500 mil CBIOs", serv: "Controle de meta, caixa e prazos" },
  { id: 4, nome: "G4 · Locais", crit: "< 100 mil CBIOs", serv: "Conformidade e prazos sem planilha" },
] as const;
