// Catálogo de softwares por setor (fonte: 09-softwares-setor.md)
export type Software = { k: string; n: string; s: string; c: string; d: string; logo: string };

export const SETORES = [
  { id: "trading", nome: "Trading e Suprimento" },
  { id: "logistica", nome: "Logística" },
  { id: "terminais", nome: "Terminais" },
  { id: "comercial", nome: "Comercial" },
  { id: "postos", nome: "Postos e Retaguarda" },
  { id: "fiscal", nome: "Fiscal e Tesouraria" },
  { id: "industrial", nome: "Industrial" },
  { id: "ia", nome: "Dados e IA" },
] as const;

export const SOFTWARES: Software[] = [
  { k: "sap-erp", n: "SAP ERP", s: "trading", c: "global", d: "ERP corporativo: compras, estoques e integração fiscal", logo: "/logos/softwares/sap-erp.svg" },
  { k: "oracle-netsuite", n: "Oracle NetSuite", s: "trading", c: "global", d: "ERP cloud do mid-market; módulos de supply e financeiro unificados", logo: "/logos/softwares/oracle-netsuite.svg" },
  { k: "allegro-horizon", n: "ION Allegro", s: "trading", c: "global", d: "ETRM: gestão de risco e posição em commodities (diesel, etanol, Brent)", logo: "/logos/softwares/allegro-horizon.svg" },
  { k: "openlink-endur", n: "Openlink Endur (ION)", s: "trading", c: "global", d: "ETRM para gestão de risco e posição em commodities (grupo ION)", logo: "/logos/softwares/openlink-endur.svg" },
  { k: "lincros", n: "Lincros (grupo Sankhya)", s: "logistica", c: "brasil", d: "TMS para gestão de transporte: CT-e/MDF-e, janelas e rastreamento", logo: "/logos/softwares/lincros.png" },
  { k: "onixsat", n: "OnixSat", s: "logistica", c: "brasil", d: "Rastreamento e telemetria de frota pesada, com consumo e nível de combustível", logo: "/logos/softwares/onixsat.png" },
  { k: "embrasat", n: "Embrasat", s: "logistica", c: "brasil", d: "Rastreamento e telemetria de frotas", logo: "/logos/softwares/embrasat.png" },
  { k: "sascar", n: "Sascar (Michelin Connected Fleet)", s: "logistica", c: "brasil", d: "Rastreamento veicular com foco em segurança da carga", logo: "/logos/softwares/sascar.svg" },
  { k: "trimble-transport", n: "Trimble Transportation", s: "logistica", c: "global", d: "TMS global: roteirização, ELD e gestão de transportadoras", logo: "/logos/softwares/trimble-transport.png" },
  { k: "salesforce", n: "Salesforce", s: "comercial", c: "global", d: "CRM para times comerciais B2B", logo: "/logos/softwares/salesforce.svg" },
  { k: "hubspot", n: "HubSpot", s: "comercial", c: "global", d: "CRM + marketing + service no pacote mid-market", logo: "/logos/softwares/hubspot.svg" },
  { k: "pipedrive", n: "Pipedrive", s: "comercial", c: "global", d: "CRM de pipeline simples para equipes de vendas externas", logo: "/logos/softwares/pipedrive.svg" },
  { k: "rd-station", n: "RD Station", s: "comercial", c: "brasil", d: "Automação de marketing e CRM brasileiro", logo: "/logos/softwares/rd-station.png" },
  { k: "dynamics-365", n: "Microsoft Dynamics 365", s: "comercial", c: "global", d: "CRM/ERP integrado ao ecossistema Microsoft", logo: "/logos/softwares/dynamics-365.svg" },
  { k: "webposto", n: "WebPosto (Quality Automação)", s: "postos", c: "brasil", d: "Retaguarda de postos: volumes, fiscal e cartão (o fornecedor se apresenta como líder de mercado)", logo: "/logos/softwares/webposto.png" },
  { k: "totvs-postos", n: "TOTVS Postos", s: "postos", c: "brasil", d: "Vertical de postos da TOTVS: retaguarda, conveniência e fiscal", logo: "/logos/softwares/totvs-postos.svg" },
  { k: "argo", n: "Argo Sistemas", s: "postos", c: "brasil", d: "Retaguarda de postos e bandeira branca", logo: "/logos/softwares/argo.png" },
  { k: "wgs", n: "WGS Systems", s: "postos", c: "brasil", d: "Retaguarda de postos e bandeira branca", logo: "/logos/softwares/wgs.png" },
  { k: "postogestor", n: "PostoGestor", s: "postos", c: "brasil", d: "Retaguarda e gestão de postos: faturamento, conveniência e relatórios", logo: "/logos/softwares/postogestor.png" },
  { k: "ftr", n: "FTR", s: "postos", c: "brasil", d: "Retaguarda de postos e automação fiscal", logo: "/logos/softwares/ftr.png" },
  { k: "acssoft", n: "ACS Soft", s: "postos", c: "brasil", d: "Automação comercial e sistemas para postos: PDV, retaguarda e fiscal", logo: "/logos/softwares/acssoft.png" },
  { k: "cbio-plataforma", n: "Plataforma CBIO (ANP/B3)", s: "fiscal", c: "brasil", d: "Emissão e aposentação de CBIOs: ambiente ANP/Serpro + sistema da B3", logo: "/logos/softwares/cbio-plataforma.svg" },
  { k: "arquivei", n: "Qive (ex-Arquivei)", s: "fiscal", c: "brasil", d: "Gestão de XML fiscal, ICMS e escrituração", logo: "/logos/softwares/arquivei.png" },
  { k: "nfe-io", n: "NFE.io", s: "fiscal", c: "brasil", d: "API de emissão e consulta de notas fiscais", logo: "/logos/softwares/nfe-io.png" },
  { k: "conta-azul", n: "Conta Azul", s: "fiscal", c: "brasil", d: "ERP/financeiro para PMEs brasileiras", logo: "/logos/softwares/conta-azul.png" },
  { k: "omie", n: "Omie", s: "fiscal", c: "brasil", d: "ERP fiscal e financeiro no cloud, forte em PME", logo: "/logos/softwares/omie.png" },
  { k: "aspen-hysys", n: "Aspen HYSYS (AspenTech, grupo Emerson)", s: "industrial", c: "global", d: "Simulação de processos em refino e bioquímica", logo: "/logos/softwares/aspen-hysys.svg" },
  { k: "honeywell-unisim", n: "Honeywell UniSim", s: "industrial", c: "global", d: "Simulação de operações e treinamento de operadores", logo: "/logos/softwares/honeywell-unisim.svg" },
  { k: "aveva", n: "AVEVA (PI System)", s: "industrial", c: "global", d: "Historiador industrial e OEE em tempo real", logo: "/logos/softwares/aveva.png" },
  { k: "siemens", n: "Siemens", s: "industrial", c: "global", d: "Automação industrial, SCADA e digital twin", logo: "/logos/softwares/siemens.png" },
  { k: "microsoft", n: "Microsoft (Power BI / Copilot)", s: "ia", c: "global", d: "BI corporativo e copiloto no Excel e no Office", logo: "/logos/softwares/microsoft.svg" },
  { k: "google-cloud", n: "Google Cloud (Gemini)", s: "ia", c: "global", d: "IA generativa e Vertex AI para agentes enterprise", logo: "/logos/softwares/google-cloud.svg" },
  { k: "aws-bedrock", n: "AWS (Bedrock)", s: "ia", c: "global", d: "Modelos foundation e infraestrutura de agentes em escala", logo: "/logos/softwares/aws-bedrock.png" },
  { k: "openai", n: "OpenAI", s: "ia", c: "global", d: "GPT para agentes de conversação, extração e análise", logo: "/logos/softwares/openai.svg" },
  { k: "anthropic", n: "Anthropic (Claude)", s: "ia", c: "global", d: "Claude para agentes de raciocínio longo e análise documental", logo: "/logos/softwares/anthropic.svg" },
  { k: "slack", n: "Slack", s: "ia", c: "global", d: "Camada de comunicação onde agentes reportam e executam", logo: "/logos/softwares/slack.svg" },
  { k: "notion", n: "Notion", s: "ia", c: "global", d: "Base de conhecimento e wikis alimentadas por IA", logo: "/logos/softwares/notion.svg" },
  { k: "github-copilot", n: "GitHub Copilot", s: "ia", c: "global", d: "Copilot de código: acelera times de TI internos", logo: "/logos/softwares/github-copilot.svg" },
  { k: "n8n", n: "n8n", s: "ia", c: "global", d: "Automação de workflows open-source para agentes", logo: "/logos/softwares/n8n.svg" },
  { k: "make", n: "Make", s: "ia", c: "global", d: "Automação no-code de integrações", logo: "/logos/softwares/make.svg" },
  { k: "zapier", n: "Zapier", s: "ia", c: "global", d: "Integração entre milhares de aplicativos, com agentes de IA", logo: "/logos/softwares/zapier.svg" },
  { k: "cursor", n: "Cursor", s: "ia", c: "global", d: "IDE com IA para desenvolvimento acelerado", logo: "/logos/softwares/cursor.svg" },
];
